version: '3.5'

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html     
      - ./configs/run.sh:/var/www/html/run.sh      
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
      - ./configs/cron/crontab:/etc/cron.d/cool-task
      - ./configs/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${HOST_EXT_PORT}:80
    networks:
      - rede

  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - ${MYSQL_EXT_PORT}:3306
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
      - ./configs/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - rede

networks:
  rede:
    driver: bridge